### ISSUE TITLE
Looking for a recommendation on how to customize the AWS region

### ISSUE THREAD

**Issue by ingojaeckel** [pottava/dockerized-aws-x-ray#1]
How do you recommend to customize the AWS region when running `pottava/xray:2.0` on AWS Beanstalk (via [Dockerrun.aws.json](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html#create_deploy_docker_v2config_dockerrun_format))? In your sample `docker-compose.yml` file, I noticed you are [suggesting to override](https://github.com/pottava/dockerized-aws-x-ray/blob/master/sample/docker-compose.yml) the CMD that is executed by the `Dockerfile`. By default, the following will run:

    ENTRYPOINT ["xray", "--config", "/xray-daemon.yaml"]
    CMD ["--region", "us-west-2"]

In docker-compose, this can be changed as follows:

    command: --region ${AWS_REGION} --local-mode

Do you have any suggestions on how to accomplish the same thing in a `Dockerrun.aws.json` file?

**Comment by pottava** [comment]
Sorry, I have no idea. I think the only way to run this image is by creating a new image from this. Like the following
```
FROM pottava/xray:3.1
CMD ["--region", "us-west-1", "--local-mode"]
```
